[2024-07-09T09:54:34.635+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: s3_to_snowflake_etl.find_latest_s3_file scheduled__2023-01-03T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
